services:
     postgres:
          image: postgres:15-alpine
          container_name: point_prevalence_postgres
          environment:
               POSTGRES_DB: point_prevalence_survey
               POSTGRES_USER: postgres
               POSTGRES_PASSWORD: password
          ports:
               - "5432:5432"
          volumes:
               - postgres_data:/var/lib/postgresql/data
          networks:
               - point_prevalence_network

     app:
          build: .
          container_name: point_prevalence_api
          ports:
               - "8080:8080"
          environment:
               - DB_HOST=postgres
               - DB_PORT=5432
               - DB_USER=postgres
               - DB_PASSWORD=password
               - DB_NAME=point_prevalence_survey
               - DB_SSLMODE=disable
               - SERVER_PORT=8080
          depends_on:
               - postgres
          networks:
               - point_prevalence_network
          volumes:
               - ./csv_files:/app/csv_files

volumes:
     postgres_data:

networks:
     point_prevalence_network:
          driver: bridge
